import * as Fate from './domain.mjs';
import {PACK_ID,SCENES} from './pack.mjs';
const copy=x=>JSON.parse(JSON.stringify(x));
const fields=(o,keys)=>Object.fromEntries(keys.filter(k=>Object.hasOwn(o,k)).map(k=>[k,copy(o[k])]));
function cleanAspect(a){const n=Fate.createAspect({id:text(a.id,200),name:text(a.name,180),kind:a.kind,freeInvokes:a.freeInvokes.map(g=>({id:text(g.id,200),authorizedActorIds:g.authorizedActorIds.map(v=>text(v,100))}))});if(a.kind==='consequence')Object.assign(n,{severity:a.severity,shifts:a.shifts,incurred:fields(a.incurred,['sceneId','sessionId','scenarioId','sessionIndex'])});return n;}
const id=()=>crypto.randomUUID();
const rng=()=>crypto.getRandomValues(new Uint32Array(1))[0]/4294967296;
function check(ok,message,status=400){if(!ok){const e=new Error(message);e.status=status;throw e;}}
function text(x,max=1000){check(typeof x==='string'&&x.trim().length>0&&x.length<=max,`Text must contain 1–${max} characters.`);return x.trim();}
function number(x,min,max){check(Number.isSafeInteger(x)&&x>=min&&x<=max,'Number is out of range.');return x;}
const context=s=>({sceneId:s.scene.id,sessionId:`session-${s.session}`,sessionIndex:s.session,scenarioId:PACK_ID});
function gm(m){check(m.role==='gm','Only the GM can make that ruling.',403);}
function char(s,m,charId){const c=s.characters.find(c=>c.id===charId);check(c,'Character not found.',404);check(m.role==='gm'||(!c.npc&&c.ownerId===m.id),'You can only act through your own character.',403);return c;}
function replace(s,c){s.characters[s.characters.findIndex(x=>x.id===c.id)]=c;}
function log(s,m,message,isPrivate=false){check(s.journal.length<2000,'This campaign journal is full. Export a backup before starting a new campaign.');s.journal.push({id:id(),author:m.name,text:message,at:new Date().toISOString(),private:isPrivate});}
function result(s,m,message){log(s,m,message);return{state:s,result:{message}};}
function activeRequest(s,requestId,status){const r=s.requests.find(r=>r.id===requestId);check(r&&r.status===status,'This action is no longer at that stage.',409);return r;}
function resolve(r){return Fate.resolveAction({action:r.action,total:r.roll.total,opposition:r.roll.opposition});}
export const fateAdapter={
 initialState({title}){return{schemaVersion:1,ruleset:'fate-accelerated',packId:PACK_ID,title,session:1,sceneIndex:0,scene:copy(SCENES[0]),inConflict:false,characters:[],aspects:SCENES[0].aspects.map(name=>Fate.createAspect({id:id(),name})),requests:[],compels:[],journal:[]};},
 project(state,member){const s=copy(state);if(member.role!=='gm'){delete s.scene.gmNotes;s.journal=s.journal.filter(e=>!e.private);}return s;},
 command(state,member,type,payload){
  const s=copy(state),p=payload||{};check(p&&typeof p==='object'&&!Array.isArray(p),'Invalid action payload.');
  switch(type){
   case 'character.create':{
    check(s.characters.length<24,'This table has reached its character limit.');check(member.role==='gm'||!s.characters.some(c=>c.ownerId===member.id),'You already have a character.');
    const c=Fate.createCharacter({id:id(),name:text(p.name,60),templateId:p.templateId});
    Object.assign(c,{ownerId:member.id,zone:s.scene.zones[0].id,pendingDamage:0,npc:member.role==='gm'&&p.npc===true});
    const ready=Fate.beginSession(c,{sessionId:`session-${s.session}`,sessionIndex:s.session});s.characters.push(ready);return result(s,member,`${c.name} joined the story.`);
   }
   case 'character.claim':{const c=s.characters.find(c=>c.id===p.characterId);check(c&&!c.npc&&c.ownerId===null,'This character is already claimed.',409);check(member.role==='gm'||!s.characters.some(c=>c.ownerId===member.id),'You already have a character.');c.ownerId=member.id;return result(s,member,`${member.name} claimed ${c.name}.`);}
   case 'character.edit':{const c=char(s,member,p.characterId);check(!s.requests.some(r=>r.characterId===c.id),'Finish pending actions before editing aspects.',409);c.aspects.find(a=>a.kind==='highConcept').name=text(p.highConcept,180);c.aspects.find(a=>a.kind==='trouble').name=text(p.trouble,180);return result(s,member,`${c.name} updated their concept and trouble (table character-edit convention).`);}
   case 'move':{const c=char(s,member,p.characterId);check(!c.takenOut&&!c.pendingDamage,'Resolve your condition before moving.');check(!s.inConflict||member.role==='gm','During a conflict, ask the GM to adjudicate movement.',403);const from=s.scene.zones.find(z=>z.id===c.zone),to=s.scene.zones.find(z=>z.id===p.zoneId);check(to&&from?.adjacent.includes(to.id),'Move to an adjacent zone; the GM resolves obstacles and longer routes.');c.zone=to.id;return result(s,member,`${c.name} moved to ${to.name}.`);}
   case 'action.propose':{
    const c=char(s,member,p.characterId);check(!c.takenOut&&!c.pendingDamage,'Resolve your condition before acting.');check(s.requests.length<30&&!s.requests.some(r=>r.characterId===c.id),'Finish your pending action first.',409);check(Fate.ACTIONS.includes(p.action)&&Fate.APPROACHES.includes(p.approach),'Choose a valid action and approach.');
    if(p.targetId){check(p.action==='attack'&&p.targetId!==c.id&&s.characters.some(t=>t.id===p.targetId),'Choose another character as target.');}
    s.requests.push({id:id(),characterId:c.id,action:p.action,approach:p.approach,intent:text(p.intent),targetId:p.targetId||null,status:'proposed'});return result(s,member,`${c.name} proposed ${p.action}: ${p.intent}`);
   }
   case 'action.cancel':{const r=s.requests.find(x=>x.id===p.requestId);check(r,'Action is no longer pending.',409);char(s,member,r.characterId);if(r.status==='rolled')gm(member);s.requests=s.requests.filter(x=>x.id!==r.id);return result(s,member,'The action was cancelled. Previously spent Fate points are not refunded.');}
   case 'action.roll':{
    gm(member);const r=activeRequest(s,p.requestId,'proposed'),c=char(s,member,r.characterId);check(!c.takenOut&&!c.pendingDamage,'Resolve the character’s pending damage first.');
    if(r.targetId){const t=s.characters.find(c=>c.id===r.targetId);check(t&&!t.pendingDamage&&!t.takenOut,'Resolve the target’s pending hit first.');}
    const bonus=p.stuntBonus??0;check([0,2].includes(bonus),'Stunt bonus must be 0 or 2.');r.opposition=number(p.opposition,-2,10);r.roll=Fate.createRoll({id:id(),character:c,action:r.action,approach:r.approach,opposition:r.opposition,stuntBonus:bonus},rng);r.outcome=resolve(r);r.status='rolled';return result(s,member,`${c.name} rolled ${r.roll.total} against ${r.opposition}. Invokes may be resolved before applying the outcome.`);
   }
   case 'action.invoke':{
    const r=activeRequest(s,p.requestId,'rolled'),c=char(s,member,r.characterId);const all=[...s.aspects,...s.characters.flatMap(x=>[...x.aspects,...Object.values(x.consequences).filter(Boolean)])];const a=all.find(a=>a.id===p.aspectId);check(a,'Choose a visible aspect.');if(p.mode==='paid')check(s.aspects.some(x=>x.id===a.id)||c.aspects.some(x=>x.id===a.id)||Object.values(c.consequences).some(x=>x?.id===a.id),'Paid hostile invokes require a GM table ruling; this control supports own or scene aspects.');
    const v=Fate.invokeAspect({character:c,roll:r.roll,aspect:a,mode:p.mode,effect:p.effect||'bonus',justification:text(p.justification,500),freeInvokeId:p.freeInvokeId},rng);replace(s,v.character);r.roll=v.roll;r.outcome=resolve(r);
    s.aspects=s.aspects.map(x=>x.id===a.id?v.aspect:x).filter(x=>!(v.removeAspect&&x.id===a.id));for(const ch of s.characters){ch.aspects=ch.aspects.map(x=>x.id===a.id?v.aspect:x);for(const k of Object.keys(ch.consequences))if(ch.consequences[k]?.id===a.id)ch.consequences[k]=v.aspect;}
    return result(s,member,`${c.name} invoked “${a.name}”: ${p.justification}. Total ${r.roll.total}.`);
   }
   case 'action.finalize':{
    gm(member);const r=activeRequest(s,p.requestId,'rolled'),c=s.characters.find(c=>c.id===r.characterId);check(c,'Acting character no longer exists.');check(!c.takenOut&&!c.pendingDamage,'Resolve the acting character’s condition before applying this action.',409);const o=resolve(r);r.outcome=o;if(o.cost)text(p.resolutionNote,1000);
    if(o.damageShifts>0&&r.targetId){const target=s.characters.find(c=>c.id===r.targetId);check(target&&!target.pendingDamage&&!target.takenOut,'Resolve the target’s existing hit first.',409);target.pendingDamage=o.damageShifts;target.pendingAttackerId=c.id;target.pendingHitId=r.id;}
    if(o.createsAspect||o.boost){check(s.aspects.length<80,'Resolve existing scene aspects before adding more.');const count=o.boost?1:o.freeInvokes;const aid=id();s.aspects.push(Fate.createAspect({id:aid,name:text(p.aspectName||`${o.boost?'Opening':'Advantage'}: ${r.intent}`.slice(0,180),180),kind:o.boost?'boost':'situation',freeInvokes:Array.from({length:count},()=>({id:id(),authorizedActorIds:[c.id]}))}));}
    s.requests=s.requests.filter(x=>x.id!==r.id);let detail=o.cost?` Success at ${o.cost} cost, agreed at the table: ${p.resolutionNote}.`:'';if(r.action==='attack'&&!r.targetId&&o.damageShifts)detail+=` ${o.damageShifts} shifts against external opposition; the GM records its consequences.`;if(r.action==='defend')detail+=' Use the opposing action to resolve ties or failure.';
    return result(s,member,`${c.name}: ${r.intent} — ${o.outcome}, total ${r.roll.total} vs ${r.opposition}.${detail}${!o.cost&&p.resolutionNote?' '+text(p.resolutionNote,1000):''}`);
   }
   case 'damage.absorb':{const c=char(s,member,p.characterId);check(c.pendingDamage>0,'There is no pending hit.');check(Array.isArray(p.consequences)&&p.consequences.length<=3,'Choose up to three consequences.');for(const x of p.consequences)text(x.name,180);const outcome=Fate.absorbDamage(c,{shifts:c.pendingDamage,stressBox:p.stressBox??null,consequences:p.consequences,context:context(s),attackerId:c.pendingAttackerId,hitId:c.pendingHitId});check(!outcome.takenOut,'That allocation does not absorb the hit. Choose more absorption or accept being taken out.');outcome.character.pendingDamage=0;delete outcome.character.pendingAttackerId;delete outcome.character.pendingHitId;replace(s,outcome.character);return result(s,member,`${c.name} absorbed ${c.pendingDamage} shifts.`);}
   case 'damage.takenOut':{const c=char(s,member,p.characterId);check(c.pendingDamage>0,'There is no pending hit.');c.pendingDamage=0;c.takenOut=true;s.requests=s.requests.filter(r=>r.characterId!==c.id);delete c.pendingAttackerId;delete c.pendingHitId;return result(s,member,`${c.name} was taken out. The table agrees the fictional consequences.`);}
   case 'scene.conflict':{gm(member);check(typeof p.active==='boolean','Invalid conflict state.');check(!s.characters.some(c=>c.pendingDamage),'Resolve pending hits first.',409);s.inConflict=p.active;return result(s,member,p.active?'A conflict began. The GM adjudicates turn order and movement.':'The conflict ended. Stress clears when the scene ends.');}
   case 'scene.advance':{gm(member);check(s.sceneIndex<SCENES.length-1,'This is the final scene. Record your ending in the journal.');check(!s.requests.length&&!s.compels.length&&!s.characters.some(c=>c.pendingDamage),'Resolve pending decisions and hits before ending the scene.',409);s.sceneIndex++;s.scene=copy(SCENES[s.sceneIndex]);s.inConflict=false;s.aspects=s.scene.aspects.map(name=>Fate.createAspect({id:id(),name}));s.characters=s.characters.map(c=>({...Fate.endScene(c),zone:s.scene.zones[0].id}));return result(s,member,`The table entered ${s.scene.title}. Stress cleared; consequences remain until eligible recovery.`);}
   case 'session.start':{gm(member);check(!s.requests.length&&!s.compels.length&&!s.characters.some(c=>c.pendingDamage),'Finish pending decisions before a new session.',409);s.session++;s.characters=s.characters.map(c=>Fate.beginSession(c,{sessionId:`session-${s.session}`,sessionIndex:s.session}));return result(s,member,`Session ${s.session} began. Fate points refreshed to at least refresh.`);}
   case 'character.milestone':{gm(member);const c=char(s,member,p.characterId);check(['significant','major'].includes(p.tier),'Choose significant or major.');const n=Fate.applyMilestone(c,{id:id(),type:p.tier,approachIncrease:p.approach});replace(s,n);return result(s,member,`${c.name} received a ${p.tier} milestone: ${p.approach} +1.`);}
   case 'character.recover':{gm(member);const c=char(s,member,p.characterId);check(!s.inConflict,'Finish the conflict before recovery.');check(['mild','moderate','severe'].includes(p.slot),'Choose a consequence severity.');const n=Fate.recoverConsequence(c,{severity:p.slot,gmApproved:true,justification:text(p.reason,1000),phase:p.slot==='mild'?'sceneEnd':p.slot==='moderate'?'sessionEnd':'scenarioEnd',context:context(s),rested:true});replace(s,n);return result(s,member,`GM confirmed ${c.name}'s ${p.slot} recovery at the required end/rest point: ${p.reason}`);}
   case 'compel.propose':{gm(member);const c=char(s,member,p.characterId);check(c.aspects.some(a=>a.id===p.aspectId),'Choose one of this character’s aspects.');check(s.compels.length<24&&!s.compels.some(x=>x.characterId===c.id),'Resolve the existing compel first.');s.compels.push({id:id(),characterId:c.id,aspectId:p.aspectId,complication:text(p.complication,1000)});return result(s,member,`GM proposed a compel to ${c.name}. No Fate points changed.`);}
   case 'compel.resolve':{const compel=s.compels.find(x=>x.id===p.compelId);check(compel,'Compel is no longer pending.',409);const c=char(s,member,compel.characterId);replace(s,Fate.resolveCompel(c,{decision:p.decision,aspectId:compel.aspectId,complication:compel.complication}));s.compels=s.compels.filter(x=>x.id!==compel.id);return result(s,member,`${c.name} ${p.decision==='accept'?'accepted':'declined'} the compel: ${compel.complication}`);}
   case 'journal.add':{const message=text(p.text,2000);if(p.private)gm(member);log(s,member,message,p.private===true);return{state:s,result:{message:'Note saved.'}};}
   default:check(false,'Unknown campaign command.');
  }
 },
 validateImport(raw){
  check(raw&&raw.schemaVersion===1&&raw.ruleset==='fate-accelerated'&&raw.packId===PACK_ID,'This backup uses an unsupported campaign format.');const s=fateAdapter.initialState({title:text(raw.title,100)});s.session=number(raw.session,1,10000);s.sceneIndex=number(raw.sceneIndex,0,2);s.scene=copy(SCENES[s.sceneIndex]);s.inConflict=raw.inConflict===true;
  check(Array.isArray(raw.characters)&&raw.characters.length<=24,'Invalid character roster.');s.characters=raw.characters.map(c=>{check(Fate.validateCharacter(c).valid,'A character in this backup is invalid.');const allowed=['schemaVersion','ruleset','id','name','appearance','approaches','aspects','stunts','refreshBase','refresh','fatePoints','stress','consequences','takenOut','lastSession','appliedMilestoneIds'];const n=Object.fromEntries(allowed.map(k=>[k,copy(c[k])]));text(n.id,100);text(n.name,60);n.aspects=n.aspects.map(cleanAspect);n.stunts=n.stunts.map(st=>fields(st,['id','name','description','kind','approach','action','bonus','condition','usedSessionId']));for(const k of ['mild','moderate','severe'])if(n.consequences[k])n.consequences[k]=cleanAspect(n.consequences[k]);if(n.lastSession){n.lastSession=fields(n.lastSession,['id','index']);check(n.lastSession.index<=s.session&&n.lastSession.id===`session-${n.lastSession.index}`,'Character session is inconsistent with campaign.');}check(s.scene.zones.some(z=>z.id===c.zone),'Invalid saved character zone.');n.ownerId=c.npc?'gm':null;n.npc=c.npc===true;n.zone=c.zone;n.pendingDamage=number(c.pendingDamage||0,0,100);if(n.pendingDamage){n.pendingAttackerId=text(c.pendingAttackerId,100);n.pendingHitId=text(c.pendingHitId,100);}return n;});check(new Set(s.characters.map(c=>c.id)).size===s.characters.length,'Duplicate character IDs.');
  check(Array.isArray(raw.aspects)&&raw.aspects.length<=80,'Invalid scene aspects.');s.aspects=raw.aspects.map(cleanAspect);
  check(Array.isArray(raw.journal)&&raw.journal.length<=2000,'Invalid journal.');s.journal=raw.journal.map(e=>({id:text(e.id,100),author:text(e.author,100),text:text(e.text,4000),at:new Date(e.at).toISOString(),private:e.private===true}));
  check(Array.isArray(raw.requests)&&raw.requests.length<=30,'Invalid pending actions.');s.requests=raw.requests.map(r=>{check(s.characters.some(c=>c.id===r.characterId)&&Fate.ACTIONS.includes(r.action)&&Fate.APPROACHES.includes(r.approach)&&['proposed','rolled'].includes(r.status),'Invalid pending action.');const n={id:text(r.id,100),characterId:r.characterId,action:r.action,approach:r.approach,intent:text(r.intent),targetId:r.targetId||null,status:r.status};check(!n.targetId||s.characters.some(c=>c.id===n.targetId),'Invalid attack target.');if(r.status==='rolled'){const a=r.roll;check(a&&a.actorId===r.characterId&&a.action===r.action&&a.approach===r.approach&&Array.isArray(a.dice)&&a.dice.length===4&&a.dice.every(d=>[-1,0,1].includes(d)),'Invalid saved dice.');n.roll={id:text(a.id,100),actorId:a.actorId,action:a.action,approach:a.approach,dice:copy(a.dice),approachBonus:number(a.approachBonus,0,5),stuntBonus:number(a.stuntBonus,0,2),invokeBonus:number(a.invokeBonus,0,10000),baseOpposition:number(a.baseOpposition,-2,10),oppositionBonus:number(a.oppositionBonus,0,10000),paidAspectIds:copy(a.paidAspectIds),usedFreeInvokes:copy(a.usedFreeInvokes)};check(Array.isArray(n.roll.paidAspectIds)&&n.roll.paidAspectIds.length<=100&&n.roll.paidAspectIds.every(x=>typeof x==='string'&&x.trim().length>0)&&new Set(n.roll.paidAspectIds).size===n.roll.paidAspectIds.length&&Array.isArray(n.roll.usedFreeInvokes)&&n.roll.usedFreeInvokes.length<=100&&n.roll.usedFreeInvokes.every(u=>u&&typeof u.aspectId==='string'&&u.aspectId.trim().length>0&&typeof u.invokeId==='string'&&u.invokeId.trim().length>0)&&new Set(n.roll.usedFreeInvokes.map(u=>JSON.stringify([u.aspectId,u.invokeId]))).size===n.roll.usedFreeInvokes.length,'Invalid invocation history.');n.roll.usedFreeInvokes=n.roll.usedFreeInvokes.map(u=>({aspectId:u.aspectId,invokeId:u.invokeId}));n.roll.total=n.roll.dice.reduce((a,b)=>a+b,0)+n.roll.approachBonus+n.roll.stuntBonus+n.roll.invokeBonus;n.roll.opposition=n.roll.baseOpposition+n.roll.oppositionBonus;n.opposition=n.roll.opposition;n.outcome=resolve(n);}return n;});
  check(new Set(s.requests.map(r=>r.id)).size===s.requests.length&&new Set(s.requests.map(r=>r.characterId)).size===s.requests.length,'Duplicate pending actions.');
  check(Array.isArray(raw.compels)&&raw.compels.length<=24,'Invalid compels.');s.compels=raw.compels.map(c=>{const ch=s.characters.find(x=>x.id===c.characterId);check(ch?.aspects.some(a=>a.id===c.aspectId),'Invalid compel character or aspect.');return{id:text(c.id,100),characterId:c.characterId,aspectId:c.aspectId,complication:text(c.complication)};});const roster=new Set(s.characters.map(c=>c.id));const aspects=[...s.aspects,...s.characters.flatMap(c=>[...c.aspects,...Object.values(c.consequences).filter(Boolean)])];check(new Set(aspects.map(a=>a.id)).size===aspects.length,'Duplicate aspect identity.');for(const a of aspects){check(a.freeInvokes.every(g=>g.authorizedActorIds.every(c=>roster.has(c))),'Unknown free-invoke recipient.');if(a.incurred)check(a.incurred.sessionIndex<=s.session&&a.incurred.sessionId===`session-${a.incurred.sessionIndex}`&&a.incurred.scenarioId===PACK_ID,'Invalid consequence time.');}check(new Set(s.compels.map(c=>c.id)).size===s.compels.length&&new Set(s.compels.map(c=>c.characterId)).size===s.compels.length,'Duplicate compels.');return s;
 }
};
