import * as Fate from './domain.mjs';
import {mechanicsAdapter} from './mechanics.mjs';
import {PACK_ID as LEGACY_ID,SCENES as LEGACY_SCENES} from './legacy/pack-v1.mjs';
const PACK_ID='user-workspace-v2';
const copy=x=>structuredClone(x), id=()=>crypto.randomUUID();
function check(ok,message,status=400){if(!ok){const e=new Error(message);e.status=status;throw e;}}
function text(x,max=1000,empty=false){check(typeof x==='string'&&x.length<=max&&(empty||x.trim()),`Text must contain ${empty?'0':'1'}–${max} characters.`);return x.trim();}
function num(x,min,max){check(Number.isSafeInteger(x)&&x>=min&&x<=max,'Number is out of range.');return x;}
function list(x,max){check(Array.isArray(x)&&x.length<=max,'Invalid list or limit exceeded.');return x;}
function unique(xs){check(new Set(xs).size===xs.length,'Duplicate identity.');}
function gm(m){check(m.role==='gm','Only the GM can use this control.',403);}
function character(s,m,cid){const c=s.characters.find(c=>c.id===cid);check(c,'Character not found.',404);check(m.role==='gm'||(!c.npc&&c.ownerId===m.id),'You can only edit your own character.',403);return c;}
function put(s,c){s.characters[s.characters.findIndex(x=>x.id===c.id)]=c;}
function scene(s,sid){const sc=s.scenes.find(x=>x.id===sid);check(sc,'Scene not found.',404);return sc;}
function zone(sc,zid){const z=sc.zones.find(x=>x.id===zid);check(z,'Zone not found.',404);return z;}
function mapUrl(value=''){const v=text(value,2000,true);if(v){let u;try{u=new URL(v);}catch{}check(u?.protocol==='https:'&&!u.username&&!u.password,'Map images must use an HTTPS URL without credentials.');}return v;}
function log(s,m,message,privateEntry=false){check(s.journal.length<2000,'Journal limit reached. Export a backup before starting another table.');s.journal.push({id:id(),author:m.name,text:message,at:new Date().toISOString(),private:privateEntry});}
function sync(s){s.scene=scene(s,s.activeSceneId);s.aspects=s.scene.aspects;s.sceneIndex=s.scenes.findIndex(x=>x.id===s.activeSceneId);return s;}
function finish(s,m,message,privateEntry=false,extra={}){log(s,m,message,privateEntry);return{state:sync(s),result:{message,...extra}};}
function ready(s){check(!s.requests.length&&!s.compels.length&&!s.characters.some(c=>c.pendingDamage)&&!s.inConflict,'Finish pending actions, compels, hits, and conflict before changing scenes.',409);}
function blankScene(title){return{id:id(),title,description:'',objective:'',gmNotes:'',zones:[{id:id(),name:'Table',description:'',adjacent:[],x:50,y:50}],aspects:[],published:false,archived:false,mapUrl:''};}
function upgrade(raw){
 if(raw.schemaVersion===2)return sync(copy(raw));
 check(raw.schemaVersion===1&&raw.packId===LEGACY_ID,'Unsupported saved workspace.');
 // Existing saves are trusted server state; retain membership and every earned rule value.
 const s=copy(raw);s.schemaVersion=2;s.scenes=LEGACY_SCENES.map((sc,index)=>({...copy(sc),zones:sc.zones.map((z,i)=>({...copy(z),x:20+i*30,y:50})),aspects:sc.id===raw.scene.id?copy(raw.aspects):sc.aspects.map(name=>Fate.createAspect({id:id(),name})),published:index<=raw.sceneIndex,archived:false,mapUrl:''}));
 const current=s.scenes.find(x=>x.id===raw.scene.id);Object.assign(current,{title:raw.scene.title,description:raw.scene.description,objective:raw.scene.objective,gmNotes:raw.scene.gmNotes});
 s.activeSceneId=current.id;s.handouts=[];s.conflict={order:[],turnIndex:0,round:1};s.characters=s.characters.map(c=>({...c,inventory:c.inventory||[]}));return sync(s);
}
function cleanAspect(a){check(a&&Array.isArray(a.freeInvokes),'Invalid aspect.');return Fate.createAspect({id:text(a.id,200),name:text(a.name,180),kind:a.kind,freeInvokes:list(a.freeInvokes,100).map(g=>({id:text(g.id,200),authorizedActorIds:list(g.authorizedActorIds,24).map(v=>text(v,100))}))});}
function cleanScene(raw){check(raw&&typeof raw==='object','Invalid scene.');const sc={id:text(raw.id,100),title:text(raw.title,100),description:text(raw.description,6000,true),objective:text(raw.objective,1000,true),gmNotes:text(raw.gmNotes,6000,true),mapUrl:mapUrl(raw.mapUrl),published:raw.published===true,archived:raw.archived===true,aspects:list(raw.aspects,80).map(cleanAspect),zones:list(raw.zones,24).map(z=>({id:text(z.id,100),name:text(z.name,80),description:text(z.description,1000,true),adjacent:list(z.adjacent,24).map(v=>text(v,100)),x:num(z.x,0,100),y:num(z.y,0,100)}))};check(sc.zones.length,'A scene requires at least one zone.');unique(sc.zones.map(z=>z.id));for(const z of sc.zones){unique(z.adjacent);check(z.adjacent.every(v=>v!==z.id&&sc.zones.some(n=>n.id===v&&n.adjacent.includes(z.id))),'Zone connections must be mutual and within their scene.');}return sc;}
export const fateAdapter={
 initialState({title}){const sc=blankScene('Untitled scene');sc.published=true;return sync({schemaVersion:2,ruleset:'fate-accelerated',packId:PACK_ID,title,session:1,scenes:[sc],activeSceneId:sc.id,handouts:[],conflict:{order:[],turnIndex:0,round:1},characters:[],requests:[],compels:[],journal:[],inConflict:false});},
 project(raw,member){const s=upgrade(raw);if(member.role!=='gm'){s.scenes=s.scenes.filter(sc=>sc.id===s.activeSceneId).map(sc=>{delete sc.gmNotes;return sc;});s.handouts=s.handouts.filter(h=>h.visible&&!h.archived);s.journal=s.journal.filter(e=>!e.private);sync(s);}return s;},
 command(raw,m,type,p={}){
  const s=upgrade(raw);check(p&&typeof p==='object'&&!Array.isArray(p),'Invalid command payload.');
  switch(type){
   case 'character.create':{check(s.characters.length<24,'This table supports 24 characters.');check(m.role==='gm'||!s.characters.some(c=>c.ownerId===m.id),'You already have a character.');if(p.npc||p.unassigned)gm(m);const c=Fate.createCustomCharacter({id:id(),name:text(p.name,60),highConcept:text(p.highConcept,180),trouble:text(p.trouble,180),aspects:list(p.aspects,3).map(a=>text(a,180)),approaches:p.approaches,appearance:text(p.appearance||'',1000,true)});Object.assign(c,{ownerId:p.unassigned?null:m.id,npc:p.npc===true,zone:s.scene.zones[0].id,pendingDamage:0,inventory:[]});s.characters.push(Fate.beginSession(c,{sessionId:`session-${s.session}`,sessionIndex:s.session}));return finish(s,m,`${c.name} joined the table.`);}
   case 'character.edit':{const c=character(s,m,p.characterId);check(!s.requests.some(r=>r.characterId===c.id)&&!s.compels.some(r=>r.characterId===c.id),'Finish pending actions and compels before editing aspects.',409);const names={[c.aspects.find(a=>a.kind==='highConcept').id]:text(p.highConcept,180),[c.aspects.find(a=>a.kind==='trouble').id]:text(p.trouble,180)};if(p.aspectNames){check(typeof p.aspectNames==='object'&&!Array.isArray(p.aspectNames),'Invalid aspect edits.');for(const [aid,name]of Object.entries(p.aspectNames))names[aid]=text(name,180);}const next=Fate.renameCharacterAspects(c,names);if(p.name!==undefined)next.name=text(p.name,60);if(p.appearance!==undefined)next.appearance=text(p.appearance,1000,true);put(s,next);return finish(s,m,`${next.name} updated their sheet.`);}
   case 'character.item.add':{const c=character(s,m,p.characterId);check(c.inventory.length<100,'Inventory supports 100 entries.');c.inventory.push({id:id(),name:text(p.name,120),quantity:num(p.quantity,1,9999),notes:text(p.notes||'',1000,true)});return finish(s,m,`${c.name} updated their inventory.`);}
   case 'character.item.remove':{const c=character(s,m,p.characterId);check(c.inventory.some(i=>i.id===p.itemId),'Item not found.',404);c.inventory=c.inventory.filter(i=>i.id!==p.itemId);return finish(s,m,`${c.name} updated their inventory.`);}
   case 'character.points':{gm(m);const c=character(s,m,p.characterId),delta=num(p.delta,-100,100),reason=text(p.reason,1000);c.fatePoints=num(c.fatePoints+delta,0,100000);return finish(s,m,`${c.name}: ${delta>=0?'+':''}${delta} Fate points. GM ruling: ${reason}`);}
   case 'character.stunt.add':{gm(m);const c=character(s,m,p.characterId);check(!s.requests.some(r=>r.characterId===c.id),'Finish pending actions before editing stunts.',409);const st={id:id(),name:text(p.name,120),description:text(p.description,1000),kind:p.kind};if(p.kind==='bonus')Object.assign(st,{approach:p.approach,action:p.action,condition:text(p.condition,500),bonus:2});put(s,Fate.addStunt(c,st));return finish(s,m,`${c.name} added a stunt. Current Fate points are unchanged.`);}
   case 'character.stunt.remove':{gm(m);const c=character(s,m,p.characterId);check(!s.requests.some(r=>r.characterId===c.id),'Finish pending actions before editing stunts.',409);put(s,Fate.removeStunt(c,p.stuntId));return finish(s,m,`${c.name} removed a stunt. Current Fate points are unchanged.`);}
   case 'character.stunt.use':{const c=character(s,m,p.characterId);put(s,Fate.useSessionStunt(c,{stuntId:p.stuntId,sessionId:`session-${s.session}`}));return finish(s,m,`${c.name} used a once-per-session stunt; the table applies its described effect.`);}
   case 'scene.create':{gm(m);check(s.scenes.length<40,'A workspace supports 40 scenes.');s.scenes.push(blankScene(text(p.title,100)));return finish(s,m,'Prepared a new scene.',true);}
   case 'scene.update':{gm(m);const sc=scene(s,p.sceneId);Object.assign(sc,{title:text(p.title,100),description:text(p.description,6000,true),objective:text(p.objective,1000,true),gmNotes:text(p.gmNotes,6000,true)});if(p.mapUrl!==undefined)sc.mapUrl=mapUrl(p.mapUrl);return finish(s,m,'Scene details saved.',sc.id!==s.activeSceneId);}
   case 'scene.activate':{gm(m);ready(s);const sc=scene(s,p.sceneId);check(!sc.archived&&sc.id!==s.activeSceneId,'Choose another unarchived scene.');s.scene.aspects=s.scene.aspects.filter(a=>a.kind!=='boost');s.activeSceneId=sc.id;sc.published=true;s.characters=s.characters.map(c=>({...Fate.endScene(c),zone:sc.zones[0].id}));s.conflict={order:[],turnIndex:0,round:1};return finish(s,m,`The table entered ${sc.title}. Stress cleared; consequences remain.`);}
   case 'scene.archive':{gm(m);const sc=scene(s,p.sceneId);check(sc.id!==s.activeSceneId,'Activate another scene before archiving this one.');check(typeof p.archived==='boolean','Choose archive or restore.');sc.archived=p.archived;return finish(s,m,p.archived?'Scene archived.':'Scene restored.',true);}
   case 'zone.add':{gm(m);const sc=scene(s,p.sceneId);check(sc.zones.length<24,'A scene supports 24 zones.');sc.zones.push({id:id(),name:text(p.name,80),description:text(p.description||'',1000,true),adjacent:[],x:num(p.x??50,0,100),y:num(p.y??50,0,100)});return finish(s,m,'Zone added.',sc.id!==s.activeSceneId);}
   case 'zone.update':{gm(m);const sc=scene(s,p.sceneId),z=zone(sc,p.zoneId);Object.assign(z,{name:text(p.name,80),description:text(p.description,1000,true),x:num(p.x,0,100),y:num(p.y,0,100)});return finish(s,m,'Zone updated.',sc.id!==s.activeSceneId);}
   case 'zone.connect':{gm(m);const sc=scene(s,p.sceneId),a=zone(sc,p.fromId),b=zone(sc,p.toId);check(a!==b&&typeof p.connected==='boolean','Choose two different zones and connection state.');for(const [from,to]of[[a,b],[b,a]])from.adjacent=p.connected?[...new Set([...from.adjacent,to.id])]:from.adjacent.filter(v=>v!==to.id);return finish(s,m,'Zone connection updated.',sc.id!==s.activeSceneId);}
   case 'zone.remove':{gm(m);const sc=scene(s,p.sceneId);zone(sc,p.zoneId);check(sc.zones.length>1,'Keep at least one zone.');check(sc.id!==s.activeSceneId||!s.characters.some(c=>c.zone===p.zoneId),'Move every character out before removing this zone.');sc.zones=sc.zones.filter(z=>z.id!==p.zoneId);for(const z of sc.zones)z.adjacent=z.adjacent.filter(v=>v!==p.zoneId);return finish(s,m,'Zone removed.',sc.id!==s.activeSceneId);}
   case 'aspect.add':{gm(m);check(s.aspects.length<80&&['situation','boost'].includes(p.kind),'Choose a situation aspect or boost; limit 80.');s.aspects.push(Fate.createAspect({id:id(),name:text(p.name,180),kind:p.kind}));return finish(s,m,'Scene aspect added. Grant free invokes when earned.');}
   case 'aspect.remove':{gm(m);check(!s.requests.length,'Finish pending actions before removing aspects.',409);check(s.aspects.some(a=>a.id===p.aspectId),'Aspect not found.');s.scene.aspects=s.aspects.filter(a=>a.id!==p.aspectId);return finish(s,m,'Scene aspect removed.');}
   case 'aspect.grant':{gm(m);const a=s.aspects.find(a=>a.id===p.aspectId);check(a,'Scene aspect not found.');check(s.characters.some(c=>c.id===p.characterId),'Character not found.');check(a.freeInvokes.length<(a.kind==='boost'?1:100),'Free invoke limit reached; boosts allow one.');a.freeInvokes.push({id:id(),authorizedActorIds:[p.characterId]});return finish(s,m,'GM granted a free invocation.');}
   case 'handout.save':{gm(m);let h=p.id?s.handouts.find(h=>h.id===p.id):null;if(p.id)check(h,'Handout not found.',404);else{check(s.handouts.length<100,'Handout limit reached.');h={id:id(),archived:false};s.handouts.push(h);}check(typeof p.visible==='boolean','Choose handout visibility.');Object.assign(h,{title:text(p.title,120),body:text(p.body,12000,true),visible:p.visible});return finish(s,m,'Handout saved.',!h.visible);}
   case 'handout.archive':{gm(m);const h=s.handouts.find(h=>h.id===p.id);check(h&&typeof p.archived==='boolean','Choose a handout and archive state.');h.archived=p.archived;return finish(s,m,'Handout archive state updated.',true);}
   case 'dice.roll':{const count=num(p.count,1,30),sides=p.sides==='F'?'F':num(p.sides,2,1000),modifier=num(p.modifier??0,-1000,1000),label=text(p.label||'Dice roll',120);const dice=Array.from({length:count},()=>{const choices=sides==='F'?3:sides;const limit=Math.floor(4294967296/choices)*choices;let n;do{n=crypto.getRandomValues(new Uint32Array(1))[0];}while(n>=limit);return n%choices+(sides==='F'?-1:1);});const total=dice.reduce((a,b)=>a+b,0)+modifier;return finish(s,m,`${label}: ${count}d${sides}${modifier>=0?'+':''}${modifier} [${dice.join(', ')}] = ${total}`,false,{dice,total});}
   case 'conflict.order':{gm(m);check(s.inConflict,'Start a conflict first.');const order=list(p.characterIds,24);unique(order);check(order.length&&order.every(v=>s.characters.some(c=>c.id===v&&!c.takenOut)),'Choose active characters for turn order.');s.conflict={order:copy(order),turnIndex:0,round:1};return finish(s,m,'Conflict turn order set.');}
   case 'conflict.next':{gm(m);check(s.inConflict&&s.conflict.order.length,'Set a conflict turn order first.');check(!s.requests.length&&!s.characters.some(c=>c.pendingDamage),'Resolve pending actions and hits before the next turn.',409);let attempts=0;do{s.conflict.turnIndex++;if(s.conflict.turnIndex>=s.conflict.order.length){s.conflict.turnIndex=0;s.conflict.round++;}attempts++;}while(attempts<s.conflict.order.length&&s.characters.find(c=>c.id===s.conflict.order[s.conflict.turnIndex])?.takenOut);check(s.characters.some(c=>s.conflict.order.includes(c.id)&&!c.takenOut),'All participants are taken out. End this conflict.');return finish(s,m,`Round ${s.conflict.round}: ${s.characters.find(c=>c.id===s.conflict.order[s.conflict.turnIndex]).name}'s turn.`);}
   case 'scene.advance':check(false,'Choose a scene from the scene library to activate.');break;
   default:{const value=mechanicsAdapter.command(s,m,type,p);value.state.scenes[value.state.sceneIndex]={...value.state.scene,aspects:value.state.aspects};if(type==='scene.conflict'&&!value.state.inConflict)value.state.conflict={order:[],turnIndex:0,round:1};value.state=sync(value.state);return value;}
  }
 },
 validateImport(raw){
  if(raw?.schemaVersion===1)return upgrade(mechanicsAdapter.validateImport(raw));
  check(raw?.schemaVersion===2&&raw.ruleset==='fate-accelerated'&&[PACK_ID,LEGACY_ID].includes(raw.packId),'Unsupported workspace backup.');
  const scenes=list(raw.scenes,40).map(cleanScene);check(scenes.length,'A workspace requires a scene.');unique(scenes.map(sc=>sc.id));const current=scenes.find(sc=>sc.id===raw.activeSceneId);check(current&&!current.archived&&current.published,'Invalid active scene.');
  const s=mechanicsAdapter.validateImport({...raw,aspects:current.aspects},{scene:current,packId:raw.packId,scenarioIds:[PACK_ID,LEGACY_ID]});
  s.schemaVersion=2;s.scenes=scenes;s.activeSceneId=current.id;s.characters=s.characters.map(c=>({...c,inventory:list(raw.characters.find(x=>x.id===c.id).inventory||[],100).map(i=>({id:text(i.id,100),name:text(i.name,120),quantity:num(i.quantity,1,9999),notes:text(i.notes,1000,true)}))}));for(const c of s.characters)unique(c.inventory.map(i=>i.id));
  const roster=new Set(s.characters.map(c=>c.id));const allAspects=[...scenes.flatMap(sc=>sc.aspects),...s.characters.flatMap(c=>[...c.aspects,...Object.values(c.consequences).filter(Boolean)])];unique(allAspects.map(a=>a.id));for(const a of allAspects)check(a.freeInvokes.every(g=>g.authorizedActorIds.every(v=>roster.has(v))),'Unknown free-invoke recipient.');for(const c of s.characters)if(c.pendingDamage)check(roster.has(c.pendingAttackerId),'Unknown pending attacker.');
  s.handouts=list(raw.handouts,100).map(h=>({id:text(h.id,100),title:text(h.title,120),body:text(h.body,12000,true),visible:h.visible===true,archived:h.archived===true}));unique(s.handouts.map(h=>h.id));
  check(raw.conflict&&typeof raw.conflict==='object','Invalid conflict state.');const order=list(raw.conflict.order,24).map(v=>text(v,100));unique(order);check(order.every(v=>roster.has(v)),'Unknown turn participant.');s.conflict={order,turnIndex:num(raw.conflict.turnIndex,0,Math.max(0,order.length-1)),round:num(raw.conflict.round,1,100000)};return sync(s);
 }
};
